set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 3.3000 -nets VDD -layer 23 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 227.3000 -nets VDD -layer 23 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 227.3400 -nets VDD -layer 25 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 3.3000 -nets VDD -layer 25 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 3.3000 -nets VDD -layer 27 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 227.3000 -nets VDD -layer 27 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 227.3400 -nets VDD -layer 29 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 3.3000 -nets VDD -layer 29 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 9.8000 -nets VSS -layer 23 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 220.8000 -nets VSS -layer 23 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 220.8400 -nets VSS -layer 25 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 9.8000 -nets VSS -layer 25 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 9.8000 -nets VSS -layer 27 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 220.8000 -nets VSS -layer 27 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 220.8400 -nets VSS -layer 29 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 9.8000 -nets VSS -layer 29 -width 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 21.3600 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.4800 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.3600 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 50.2400 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 60.1200 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 69.2400 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.1200 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 89.0000 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 98.8800 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 108.7600 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 117.8800 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 127.7600 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 137.6400 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 147.5200 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 157.4000 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 166.5200 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 176.4000 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 186.2800 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 196.1600 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 205.2800 -nets VDD  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 25.3600 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.4800 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.3600 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.2400 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.1200 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.2400 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 83.1200 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 93.0000 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 102.8800 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 112.7600 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 121.8800 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 131.7600 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 141.6400 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 151.5200 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 161.4000 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 170.5200 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 180.4000 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 190.2800 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 200.1600 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 209.2800 -nets VSS  -layer 21 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 21.7400 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 30.8600 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.9800 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 50.6200 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 59.7400 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 68.8600 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.5000 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 88.6200 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 99.2600 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 108.3800 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 117.5000 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 128.1400 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 137.2600 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 147.9000 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 157.0200 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 166.1400 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 176.7800 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 185.9000 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 196.5400 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 205.6600 -nets VDD  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 25.7400 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.8600 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.9800 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.6200 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 63.7400 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.8600 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 83.5000 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 92.6200 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 103.2600 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 112.3800 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 121.5000 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 132.1400 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 141.2600 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 151.9000 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 161.0200 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 170.1400 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 180.7800 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 189.9000 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 200.5400 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 209.6600 -nets VSS  -layer 23 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 20.9800 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.1000 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.7400 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.8600 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 60.5000 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 69.6200 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 78.7400 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 89.3800 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 98.5000 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 109.1400 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 118.2600 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 127.3800 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 138.0200 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 147.1400 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 157.7800 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 166.9000 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 176.0200 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 186.6600 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 195.7800 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 204.9000 -nets VDD  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 24.9800 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.1000 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.7400 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.8600 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.5000 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 73.6200 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 82.7400 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 93.3800 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 102.5000 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 113.1400 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 122.2600 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 131.3800 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 142.0200 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 151.1400 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 161.7800 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 170.9000 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 180.0200 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 190.6600 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 199.7800 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 208.9000 -nets VSS  -layer 25 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 20.2200 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.3400 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.5000 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 50.6200 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 59.7400 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 68.8600 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 77.9800 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 90.1400 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 99.2600 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 108.3800 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 117.5000 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 126.6200 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 138.7800 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 147.9000 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 157.0200 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 166.1400 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 175.2600 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 187.4200 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 196.5400 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 205.6600 -nets VDD  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 24.2200 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 33.3400 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.5000 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.6200 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 63.7400 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.8600 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.9800 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 94.1400 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 103.2600 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 112.3800 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 121.5000 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 130.6200 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 142.7800 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 151.9000 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 161.0200 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 170.1400 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 179.2600 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 191.4200 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 200.5400 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 209.6600 -nets VSS  -layer 27 -width 2.5000 -pitch_within_group 9.7140 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VDD
create_power_straps  -direction vertical  -start_at 21.7400 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.8600 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.9800 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.1000 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.2600 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.3800 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.5000 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 88.6200 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 97.7400 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 109.9000 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 119.0200 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 128.1400 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 137.2600 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 146.3800 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 158.5400 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 167.6600 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 176.7800 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 185.9000 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 195.0200 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 204.1400 -nets VDD  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 229.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VSS
create_power_straps  -direction vertical  -start_at 25.7400 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.8600 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.9800 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.1000 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 65.2600 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 74.3800 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 83.5000 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 92.6200 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 101.7400 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 113.9000 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 123.0200 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 132.1400 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 141.2600 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 150.3800 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 162.5400 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 171.6600 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 180.7800 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 189.9000 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 199.0200 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 208.1400 -nets VSS  -layer 29 -width 2.5000 -pitch_within_group 9.7160 -start_low_ends coordinate  -start_low_ends_coordinate 7.3000 -start_high_ends coordinate  -start_high_ends_coordinate 223.3000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
